import LocalizedStrings from "react-localization";

export let content = new LocalizedStrings({
    kz: {
        lang: 'kz',
        onLanguage: 'Қазақша',
        fullName: 'Алматының аймақтық коммуникациялар қызметі',
        home: 'Басты',
        news: 'Жаңалықтар',
        video: 'Видео',
        videoGallery: 'Видеогалерея',
        photo: 'Фото',
        photoGallery: 'Фотогалерея',
        rsk: 'AAK',
        briefings: 'Брифингтер',
        sendQuestion: 'Сұрақ жіберу',
        accreditation: 'Брифингті аккредиттеу',
        contact: 'Байланыс',
        answers: 'Сұрақтарға жауаптар',
        today: 'бүгін',
        tomorrow: 'ертең',
        seeMore: 'толығырақ көру',
        seeAll: 'Толық көру',
        media: 'Медиагалерея',
        otherVideos: 'Басқа видеолар',
        otherNews: 'Басқа жаңалықтар',
        FAQ: 'Сұрақтар мен жауаптар',
        AllRights: 'Барлық құқықтар қорғалған © 2021 ААКҚ',
        press: 'Баспасөз хабарламалар',
        names: 'Аты-жөні',
        phoneNum: 'Телефон нөмірі',
        Media: 'БАҚ',
        organization: 'Заңды тұлға болса, Ұйым',
        entity: 'Заңды тұлға',
        individual: 'Жеке тұлға',
        onlineRequestToBriefing: 'Брифинг өткізуге өтініш',
        interestedQuests: 'Қызықтыратын сұрақтар',
        requestSent: 'Өтініш жіберілді',
        sendRequest: 'Өтінішті жіберу',
        error: 'Қателік',
        errorMsg: 'Бос орындарды толтырыңыз!'
    },
    ru: {
        lang: 'ru',
        onLanguage: 'Русский',
        fullName: 'Региональная служба коммуникаций Алматы',
        home: 'Главная',
        news: 'Новости',
        video: 'Видео',
        videoGallery: 'Видеогалерея',
        photo: 'Фото',
        photoGallery: 'Фотогалерея',
        rsk: 'РСК',
        briefings: 'Брифинги',
        sendQuestion: 'Отправить вопрос',
        accreditation: 'Аккредитация на брифинг',
        contact: 'Контакты',
        answers: 'Ответы на вопросы',
        today: 'сегодня',
        tomorrow: 'завтра',
        seeMore: 'показать больше',
        seeAll: 'Смотреть все',
        media: 'Медиагалерея',
        otherVideos: 'Другие видео',
        otherNews: 'Другие новости',
        FAQ: 'Вопросы и ответы',
        AllRights: 'Все права защищены © 2021 РСКА',
        press: 'Пресс-анонсы',
        names: 'ФИО',
        phoneNum: 'Номер телефона',
        Media: 'СМИ',
        organization: 'Организация, если юр.лицо',
        entity: 'Юридическое лицо',
        individual: 'Физическое лицо',
        onlineRequestToBriefing: 'Онлайн заявка на проведение брифинга',
        interestedQuests: 'Интересующие вопросы',
        requestSent: 'Запрос отправлен',
        sendRequest: 'Отправить заявку',
        error: 'Ошибка',
        errorMsg: 'Заполните все поля!'
    }, 
    en: {
        lang: 'en',
        onLanguage: 'English',
        fullName: 'Regional Communications Service Almaty',
        home: 'Home',
        news: 'News',
        video: 'Video',
        videoGallery: 'Videogallery',
        photo: 'Photo',
        photoGallery: 'Photogallery',
        rsk: 'RCS',
        briefings: 'Briefings',
        sendQuestion: 'Ask questions',
        accreditation: 'Briefing Accreditation',
        contact: 'Contacts',
        answers: 'Answers',
        today: 'today',
        tomorrow: 'tomorrow',
        seeMore: 'see more',
        seeAll: 'See All',
        media: 'Media',
        otherVideos: 'Other videos',
        otherNews: 'Other news',
        FAQ: 'Questions and answers',
        AllRights: 'All Rights Reserved © 2021 RCSA',
        press: 'Press announcements',
        names: 'Media',
        phoneNum: 'Phone number',
        Media: 'Media',
        organization: 'Organization(for entities)',
        entity: 'entity',
        individual: 'individual',
        onlineRequestToBriefing: 'Online request for a briefing',
        interestedQuests: 'Interested questions',
        requestSent: 'Request sent!',
        sendRequest: 'Send request',
        error: 'Error',
        errorMsg: 'Fill in all the fields!'
    }
})